4.40/DFar.Plugin.Widgets.Flixmedia/Models/FlixmediaConfigModel.cs
using Nop.Web.Framework.Mvc.ModelBinding;

namespace DFar.Plugin.Widgets.Flixmedia.Models
{
    public class FlixmediaConfigModel
    {
        [NopResourceDisplayName(FlixmediaLocales.FlixID)]
        public string FlixID { get; set; }

        [NopResourceDisplayName(FlixmediaLocales.WidgetZone)]
        public string WidgetZone { get; set; }
    }
}

4.40/DFar.Plugin.Widgets.Flixmedia/Models/ScriptModel.cs
namespace DFar.Plugin.Widgets.Flixmedia.Models
{
    public class ScriptModel
    {
        public string Id { get; set; }
        public string Brand { get; set; }
        public string Sku { get; set; }
    }
}

4.40/DFar.Plugin.Widgets.Flixmedia/Components/WidgetsFlixmediaViewComponent.cs
using Nop.Services.Logging;
using Microsoft.AspNetCore.Mvc;
using Nop.Web.Framework.Components;
using Nop.Core;
using System.Threading.Tasks;
using Nop.Web.Framework.Infrastructure;
using DFar.Plugin.Widgets.Flixmedia.Models;
using Nop.Web.Models.Catalog;
using System.Linq;
using Nop.Services.Catalog;

namespace DFar.Plugin.Widgets.Flixmedia.Components
{
    public class WidgetsFlixmediaViewComponent : NopViewComponent
    {
        private readonly FlixmediaSettings _settings;
        private readonly ILogger _logger;
        private readonly IWebHelper _webHelper;

        public WidgetsFlixmediaViewComponent(
            FlixmediaSettings settings,
            ILogger logger,
            IWebHelper webHelper
        )
        {
            _settings = settings;
            _logger = logger;
            _webHelper = webHelper;
        }

        public async Task<IViewComponentResult> InvokeAsync(string widgetZone, object additionalData = null)
        {
            if (!_settings.IsValid())
            {
                await _logger.ErrorAsync("Widgets.Flixmedia: Flix ID is required to be " +
                              "set to enable product syndication.");
                return Content("");
            }

            if (widgetZone == _settings.WidgetZone)
            {
                return View("~/Plugins/Widgets.Flixmedia/Views/ContentDisplay.cshtml");
            }
            if (widgetZone == PublicWidgetZones.ProductDetailsBottom)
            {
                var productDetailsModel = additionalData as ProductDetailsModel;
                var model = new ScriptModel()
                {
                    Id = _settings.FlixID,
                    Brand = productDetailsModel.ProductManufacturers.FirstOrDefault()?.Name ?? "",
                    Sku = productDetailsModel.Sku
                };
                return View("~/Plugins/Widgets.Flixmedia/Views/Script.cshtml", model);
            }

            await _logger.ErrorAsync($"Widgets.Flixmedia: No view provided for widget zone {widgetZone}");
            return Content("");
        }
    }
}

4.40/DFar.Plugin.Widgets.Flixmedia/Controllers/FlixmediaController.cs
using DFar.Plugin.Widgets.Flixmedia.Models;
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System.Threading.Tasks;

namespace DFar.Plugin.Widgets.Flixmedia.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    [AutoValidateAntiforgeryToken]
    public class FlixmediaController : BasePluginController
    {
        private readonly FlixmediaSettings _settings;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly ISettingService _settingService;

        public FlixmediaController(
            FlixmediaSettings settings,
            ISettingService settingService,
            ILocalizationService localizationService,
            INotificationService notificationService
        )
        {
            _settings = settings;
            _settingService = settingService;
            _localizationService = localizationService;
            _notificationService = notificationService;
        }

        public ActionResult Configure()
        {
            return View(
                "~/Plugins/Widgets.Flixmedia/Views/Configure.cshtml",
                _settings.ToModel());
        }

        [HttpPost]
        
        public async Task<IActionResult> Configure(FlixmediaConfigModel model)
        {
            if (!ModelState.IsValid)
            {
                return Configure();
            }

            await _settingService.SaveSettingAsync(FlixmediaSettings.FromModel(model));

            _notificationService.SuccessNotification(
                await _localizationService.GetResourceAsync("Admin.Plugins.Saved")
            );

            return Configure();
        }
    }
}

4.40/DFar.Plugin.Widgets.Flixmedia/Views/Configure.cshtml
@model DFar.Plugin.Widgets.Flixmedia.Models.FlixmediaConfigModel

@{
    Layout = "_ConfigurePlugin";
}

<form asp-controller="Flixmedia" asp-action="Configure" method="post">
	<section class="content">
		<div class="container-fluid">			
				<div class="card card-default">
					<div class="card-body">
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="FlixID" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="FlixID" />
								<span asp-validation-for="FlixID"></span>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-3">
								<nop-label asp-for="WidgetZone" />
							</div>
							<div class="col-md-9">
								<nop-editor asp-for="WidgetZone" />
								<span asp-validation-for="WidgetZone"></span>
							</div>
						</div>
						<div class="form-group row">
                            <div class="col-md-9 offset-md-3">
                                <button type="submit" name="save" class="btn btn-primary">@T("Admin.Common.Save")</button>
                            </div>
						</div>
					</div>
				</div>			
		</div>
	</section>
</form>

4.40/DFar.Plugin.Widgets.Flixmedia/Views/ContentDisplay.cshtml
<div id="flix-inpage"></div>

4.40/DFar.Plugin.Widgets.Flixmedia/Views/Script.cshtml
@model DFar.Plugin.Widgets.Flixmedia.Models.ScriptModel

<script type="text/javascript" src="//media.flixfacts.com/js/loader.js" data-flix-distributor="@Model.Id" data-flix-language="us" data-flix-brand="@Model.Brand" data-flix-mpn="@Model.Sku" data-flix-inpage="flix-inpage" async></script>